language: objective-c
xcode_workspace: Example/ShitLib.xcworkspace
xcode_scheme: ShitLib-Example
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
podfile: Example/Podfile
script:
  - pod lib lint
after_success:
  - cd Example
  - bash <(curl -s https://codecov.io/bash) -J 'ShitLib-Example'
