language: objective-c
osx_image: xcode10
xcode_project: ShitLib.xcodeproj
xcode_scheme: ShitLib iOS
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gem install cocoapods --pre
  - pod lib lint
